site_name: '星城芒格'
site_description: '欢迎来到星城芒格的数据投资者站'
repo_url: 'https://github.com/carlosperate/jekyll-theme-rtd'
repo_name: 'GitHub'
docs_dir: ['data','option']
site_dir: '_site_mkdocs/'
copyright: '星城芒格'
theme:
  name: readthedocs
  include_homepage_in_sidebar: false
  prev_next_buttons_location: 'both'
  logo: assets/img/jekyll-rtd-logo-250px.jpg
extra:
  version: '1.4.0'
